{
 "title": "Beds",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "bed", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "$bed Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "repeat": "bed",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "$bed Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "$bed Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "$bed Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "$bed Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "$bed Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "$bed Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "$bed Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "$bed Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "$bed Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"$bed\"}"
    }
   ]
  },
  { "title": "$bed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "bed" },
  {
   "title": "O2 Level [mmHg]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "mmHg" }
   ],
   "targets": [
    {
     "expr": "o2_mmHg{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "Heart Rate [BPM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "BPM" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(heart_rate_bpm{instance=\"$bed\"}[1m])"
    }
   ]
  },
  { "title": "$bed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "O2 Level [mmHg]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "mmHg" }
   ],
   "targets": [
    {
     "expr": "o2_mmHg{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "Heart Rate [BPM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "BPM" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(heart_rate_bpm{instance=\"$bed\"}[1m])"
    }
   ]
  },
  { "title": "$bed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "O2 Level [mmHg]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "mmHg" }
   ],
   "targets": [
    {
     "expr": "o2_mmHg{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "Heart Rate [BPM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "BPM" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(heart_rate_bpm{instance=\"$bed\"}[1m])"
    }
   ]
  },
  { "title": "$bed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "O2 Level [mmHg]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "mmHg" }
   ],
   "targets": [
    {
     "expr": "o2_mmHg{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "Heart Rate [BPM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "BPM" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(heart_rate_bpm{instance=\"$bed\"}[1m])"
    }
   ]
  },
  { "title": "$bed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "O2 Level [mmHg]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "mmHg" }
   ],
   "targets": [
    {
     "expr": "o2_mmHg{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "Heart Rate [BPM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "BPM" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(heart_rate_bpm{instance=\"$bed\"}[1m])"
    }
   ]
  },
  { "title": "$bed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "O2 Level [mmHg]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "mmHg" }
   ],
   "targets": [
    {
     "expr": "o2_mmHg{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "Heart Rate [BPM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "BPM" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(heart_rate_bpm{instance=\"$bed\"}[1m])"
    }
   ]
  },
  { "title": "$bed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "O2 Level [mmHg]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "mmHg" }
   ],
   "targets": [
    {
     "expr": "o2_mmHg{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "Heart Rate [BPM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "BPM" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(heart_rate_bpm{instance=\"$bed\"}[1m])"
    }
   ]
  },
  { "title": "$bed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "O2 Level [mmHg]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "mmHg" }
   ],
   "targets": [
    {
     "expr": "o2_mmHg{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "Heart Rate [BPM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "BPM" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(heart_rate_bpm{instance=\"$bed\"}[1m])"
    }
   ]
  },
  { "title": "$bed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "O2 Level [mmHg]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "mmHg" }
   ],
   "targets": [
    {
     "expr": "o2_mmHg{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "Heart Rate [BPM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "BPM" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(heart_rate_bpm{instance=\"$bed\"}[1m])"
    }
   ]
  },
  { "title": "$bed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "O2 Level [mmHg]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "mmHg" }
   ],
   "targets": [
    {
     "expr": "o2_mmHg{instance=\"$bed\"}"
    }
   ]
  },
  {
   "title": "Heart Rate [BPM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "BPM" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(heart_rate_bpm{instance=\"$bed\"}[1m])"
    }
   ]
  }
 ]
}